config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users, except: [:new, :create] do
    resources :posts
    resources :messages
  end
  get '/registrations/new', to: 'registrations#new'
  post '/users', to: 'registrations#create'
  get '/confirm/:id', to: 'confirmations#update', as: :confirmation
  get '/confirmations/confirmation/:id', to: 'confirmations#unconfirmed_registration'
  get '/confirmations/confirmation/send/:id', to: 'confirmations#send_confirmation_email', as: :resend_confirmation
  get '/login', to: 'sessions#new'
  get '/confirm-friendships/:friend_id/:requestor_id', to: 'confirmations#confirm_friendships', as: :confirm_friendships

  resources :friendships
  resource :sessions
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :receiver_id, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @sent_messages = Message.where(:sender_id => current_user.id)
    @received_messages = Message.where(:receiver_id => current_user.id)
  end

  def new
    @message = Message.new
    @user = current_user
    @friends = SocialGraph.new(@user).friends_for
  end

  def create
    message = Message.new(:sender_id => current_user.id,
                          :receiver_id => params[:message][:receiver_id],
                          :subject => params[:message][:subject],
                          :body => params[:message][:body])
    if message.save
      redirect_to user_messages_path(current_user), notice: "Message successfully sent!"
    else
      redirect_to user_messages_path(current_user), notice: 'You must specify a friend to send a message to'
    end
  end

end

app/views/messages/index.html.erb
<div class="messages-container">
  <p><%= link_to 'Send a Message', new_user_message_path(current_user) %></p>

  <h2>My Messages</h2>

  <h2>Received Messages:</h2>

  <div class="message_list" data-container="all-received">
  </div>

  <h2>Sent Messages:</h2>

  <div class="message_list" data-container="all-sent">
  </div>

</div>

<script>
  var receivedMessagesJSON = <%= raw messages_json(@received_messages) %>;
  var sentMessagesJSON = <%= raw messages_json(@sent_messages) %>;

  function displayMessages() {
    $.each(receivedMessagesJSON, function () {
      var $messageDiv = $("<div class='received-message' data-display='received'>");
      var $html = $(JST['templates/show_received'](this));
      $messageDiv.append($html);

      new MessageView(this, $messageDiv);

      $("[data-container=all-received]").append($messageDiv);
    })

    $.each(sentMessagesJSON, function () {
      var $messageDiv = $("<div class='sent-message' data-display='sent'>");
      var $html = $(JST['templates/show_sent'](this));
      $messageDiv.append($html);

      new MessageView(this, $messageDiv);

      $("[data-container=all-sent]").append($messageDiv);
    })
  }

  $(document).ready(displayMessages());
</script>

app/views/messages/new.html.erb
<div id="new-message">
  <%= form_for [@user, @message] do |f| %>
    <p><%= f.label 'To', class: 'registration_label' %>
    <%= f.collection_select :receiver_id, @friends, :id, :full_name %></p>

    <p><%= f.label :subject, class: 'registration_label' %>
    <%= f.text_field :subject %></p>

    <p><%= f.label :body, 'Message', class: 'registration_label' %>
    <%= f.text_area :body %></p>

    <p><%= f.submit 'Send Message' %></p>
  <% end %>
</div>