config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users, except: [:new, :create] do
    resources :posts
    resources :messages
  end
  get '/registrations/new', to: 'registrations#new'
  post '/users', to: 'registrations#create'
  get '/confirm/:id', to: 'confirmations#update', as: :confirmation
  get '/confirmations/confirmation/:id', to: 'confirmations#unconfirmed_registration'
  get '/confirmations/confirmation/send/:id', to: 'confirmations#send_confirmation_email', as: :resend_confirmation
  get '/login', to: 'sessions#new'
  get '/confirm-friendships/:friend_id/:requestor_id', to: 'confirmations#confirm_friendships', as: :confirm_friendships

  resources :friendships
  resource :sessions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G2SocialNetwork</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto|Open+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="body_wrapper">
  <header>
    <div class="nav-container">
      <div id="left_nav"><a href="/">Bradtke's Book</a></div>
      <div id="right_nav">
        <% if current_user %>
          <%= link_to image_tag('mail.png'), user_messages_path(current_user), {:id => 'messages'} %>
          <%= link_to "All Users", users_path %>
          <%= link_to current_user.email, user_path(current_user) %>
          <%= link_to "Logout", sessions_path, method: :delete, class:"logout" %>
        <% else %>
          <a href="/registrations/new" class="register">Register</a>
          <a href="/login" class="login">Login</a>
        <% end %>
      </div>
    </div>
  </header>
  <% if flash.present? %>
    <div class="flash_messages">
      <%= flash[:register_message] %>
      <%= flash[:login_message] %>
      <%= flash[:message] %>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="body_container">
    <div class="inner_container">
      <%= yield %>
    </div>
  </div>
  <footer>

  </footer>
</div>
</body>
</html>